# Generated by Django 3.1 on 2023-12-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2025, '2023-24'), (2024, '2022-23'), (2023, '2021-20'), (2022, '2020-21'), (2021, '2019-20'), (2020, '2018-19'), (2019, '2017-18')])),
                ('name', models.CharField(max_length=20)),
                ('admission_serial', models.CharField(max_length=20, null=True)),
                ('college_roll', models.CharField(max_length=10, null=True)),
                ('serial', models.CharField(max_length=20)),
                ('contact_number', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('transection_id', models.IntegerField(null=True)),
                ('father', models.CharField(max_length=20, null=True)),
                ('mother', models.CharField(max_length=20, null=True)),
                ('present_address', models.CharField(max_length=400, null=True)),
                ('permanent_address', models.CharField(max_length=400, null=True)),
                ('blood_group', models.CharField(choices=[('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('o+', 'O+'), ('o-', 'O-'), ('ab+', 'AB+'), ('ab-', 'AB-')], max_length=3, null=True)),
                ('institutional_background', models.CharField(max_length=100, null=True)),
                ('background_club_Activities', models.CharField(max_length=250, null=True)),
                ('competitions', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
