# Generated by Django 3.1 on 2023-12-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='transection_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
