# Generated by Django 4.2.16 on 2024-11-07 17:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_member_uniqueid'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='sms_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='uniqueID',
            field=models.CharField(blank=True, default=uuid.UUID('7f8dc9c6-0f20-4687-b372-85cedac15137'), max_length=36),
        ),
        migrations.AlterField(
            model_name='member',
            name='year',
            field=models.IntegerField(),
        ),
    ]
